FROM postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD docker
ENV POSTGRES_DB twitch

# docker build -f Dockerfile_psql -t evans1947/postgres_image .
# docker run evans1947/postgres_image
# pg_ctl -D /var/lib/postgresql/data -l logfile start

# or just run:
# docker run -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=docker -e POSTGRES_DB=twitch library/postgres